name: Deploy to App Engine
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}