name: Dev

on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          TEST_VAR: ${{ secrets.TEST_VAR }}
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app/app.yaml
          project_id: ${{ secrets.DEV_GCP_PROJECT }}
          credentials: ${{ secrets.DEV_GCP_SA_KEY }}